export const SIZING_OPTIONS = ["small", "medium", "large"];

export const SPACING_OPTIONS = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "auto",
  "x-0",
  "x-1",
  "x-2",
  "x-3",
  "x-4",
  "x-5",
  "x-6",
  "x-7",
  "x-8",
  "x-9",
  "x-auto",
  "y-0",
  "y-1",
  "y-2",
  "y-3",
  "y-4",
  "y-5",
  "y-6",
  "y-7",
  "y-8",
  "y-9",
  "y-auto",
  "t-0",
  "t-1",
  "t-2",
  "t-3",
  "t-4",
  "t-5",
  "t-6",
  "t-7",
  "t-8",
  "t-9",
  "t-auto",
  "r-0",
  "r-1",
  "r-2",
  "r-3",
  "r-4",
  "r-5",
  "r-6",
  "r-7",
  "r-8",
  "r-9",
  "r-auto",
  "b-0",
  "b-1",
  "b-2",
  "b-3",
  "b-4",
  "b-5",
  "b-6",
  "b-7",
  "b-8",
  "b-9",
  "b-auto",
  "l-0",
  "l-1",
  "l-2",
  "l-3",
  "l-4",
  "l-5",
  "l-6",
  "l-7",
  "l-8",
  "l-9",
  "l-auto",
];

export const ANIMATION_TYPE_OPTIONS = [
  "fade-in-top",
  "fade-in-right",
  "fade-in-bottom",
  "fade-in-left",
  "fade-out-top",
  "fade-out-right",
  "fade-out-bottom",
  "fade-out-left",
];

export const ANIMATION_DELAY_OPTIONS = [
  100, 200, 300, 400, 500, 600, 700, 800, 900, 1000,
];

export const DAY_OPTIONS = [
  { label: "01", value: "01" },
  { label: "02", value: "02" },
  { label: "03", value: "03" },
  { label: "04", value: "04" },
  { label: "05", value: "05" },
  { label: "06", value: "06" },
  { label: "07", value: "07" },
  { label: "08", value: "08" },
  { label: "09", value: "09" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
  { label: "14", value: "14" },
  { label: "15", value: "15" },
  { label: "16", value: "16" },
  { label: "17", value: "17" },
  { label: "18", value: "18" },
  { label: "19", value: "19" },
  { label: "20", value: "20" },
  { label: "21", value: "21" },
  { label: "22", value: "22" },
  { label: "23", value: "23" },
  { label: "24", value: "24" },
  { label: "25", value: "25" },
  { label: "26", value: "26" },
  { label: "27", value: "27" },
  { label: "28", value: "28" },
  { label: "29", value: "29" },
  { label: "30", value: "30" },
  { label: "31", value: "31" },
];
export const MONTH_OPTIONS = [
  { label: "JAN", value: "01" },
  { label: "FEB", value: "02" },
  { label: "MAR", value: "03" },
  { label: "APR", value: "04" },
  { label: "MAY", value: "05" },
  { label: "JUN", value: "06" },
  { label: "JUL", value: "07" },
  { label: "AUG", value: "08" },
  { label: "SEP", value: "09" },
  { label: "OCT", value: "10" },
  { label: "NOV", value: "11" },
  { label: "DEC", value: "12" },
];

const startYear = 1924;
const endYear = 2024;

export const YEAR_OPTIONS = Array.from(
  { length: endYear - startYear + 1 },
  (_, index) => {
    const year = startYear + index;
    return { label: String(year), value: String(year) };
  }
).reverse();
